In [13]:
# Guardamos nuestra API Key personal extraida para RAWG
api_key = os.getenv("OPENAI_API_KEY")
api_key

'74c8e14f7976452ebdbdc1fcf6b714c9'

In [9]:
# Importamos librerias
import pandas as pd
import os
import urllib.request, json, csv
import numpy as np
from tqdm import tqdm_notebook as tqdm

import requests

import os

import json

import pandas as pd

import csv

import datetime
import dateutil.parser
import unicodedata

import time
import requests

### Part A — General Exploration

How many games does RAWG have registered in total?

Print the number with a clear message.

El procedimiento es, en primer lugar jalar la url donde esta la sección juegos con nustra API key para luego descargarlo en un formato JSON. De ahi vemos las keys de jugos para ver que existe una con el nombre count que alberga el conteo de todos los juegos registrados por RAWG. Finalmente con un print mostramos la data de cuantos juegos han sido contados.

In [ ]:
url = f"https://api.rawg.io/api/games?key={api_key}"
info = requests.get(url)

In [ ]:
juegos = info.json()
juegos

{'count': 898364,
 'next': 'https://api.rawg.io/api/games?key=74c8e14f7976452ebdbdc1fcf6b714c9&page=2',
 'previous': None,
 'results': [{'id': 3498,
   'slug': 'grand-theft-auto-v',
   'name': 'Grand Theft Auto V',
   'released': '2013-09-17',
   'tba': False,
   'background_image': 'https://media.rawg.io/media/games/20a/20aa03a10cda45239fe22d035c0ebe64.jpg',
   'rating': 4.47,
   'rating_top': 5,
   'ratings': [{'id': 5,
     'title': 'exceptional',
     'count': 4422,
     'percent': 58.95},
    {'id': 4, 'title': 'recommended', 'count': 2462, 'percent': 32.82},
    {'id': 3, 'title': 'meh', 'count': 471, 'percent': 6.28},
    {'id': 1, 'title': 'skip', 'count': 146, 'percent': 1.95}],
   'ratings_count': 7365,
   'reviews_text_count': 74,
   'added': 22549,
   'added_by_status': {'yet': 560,
    'owned': 12877,
    'beaten': 6489,
    'toplay': 652,
    'dropped': 1192,
    'playing': 779},
   'metacritic': 92,
   'playtime': 74,
   'suggestions_count': 450,
   'updated': '2026-04-06T23:26:14',
   'user_game': None,
   'reviews_count': 7501,
   'saturated_color': '0f0f0f',
   'dominant_color': '0f0f0f',
   'platforms': [{'platform': {'id': 187,
      'name': 'PlayStation 5',
      'slug': 'playstation5',
      'image': None,
      'year_end': None,
      'year_start': 2020,
      'games_count': 1462,
      'image_background': 'https://media.rawg.io/media/games/34b/34b1f1850a1c06fd971bc6ab3ac0ce0e.jpg'},
     'released_at': '2013-09-17',
     'requirements_en': None,
     'requirements_ru': None},
    {'platform': {'id': 186,
      'name': 'Xbox Series S/X',
      'slug': 'xbox-series-x',
      'image': None,
      'year_end': None,
      'year_start': 2020,
      'games_count': 1241,
      'image_background': 'https://media.rawg.io/media/games/b4a/b4adf80c36e267b35acc3497ed2af19c.jpg'},
     'released_at': '2013-09-17',
     'requirements_en': None,
     'requirements_ru': None},
    {'platform': {'id': 16,
      'name': 'PlayStation 3',
      'slug': 'playstation3',
      'image': None,
      'year_end': None,
      'year_start': None,
      'games_count': 3195,
      'image_background': 'https://media.rawg.io/media/games/7fa/7fa0b586293c5861ee32490e953a4996.jpg'},
     'released_at': '2013-09-17',
     'requirements_en': None,
     'requirements_ru': None},
    {'platform': {'id': 4,
      'name': 'PC',
      'slug': 'pc',
      'image': None,
      'year_end': None,
      'year_start': None,
      'games_count': 560648,
      'image_background': 'https://media.rawg.io/media/games/736/73619bd336c894d6941d926bfd563946.jpg'},
     'released_at': '2013-09-17',
     'requirements_en': {'minimum': 'Minimum:OS: Windows 10 64 Bit, Windows 8.1 64 Bit, Windows 8 64 Bit, Windows 7 64 Bit Service Pack 1, Windows Vista 64 Bit Service Pack 2* (*NVIDIA video card recommended if running Vista OS)Processor: Intel Core 2 Quad CPU Q6600 @ 2.40GHz (4 CPUs) / AMD Phenom 9850 Quad-Core Processor (4 CPUs) @ 2.5GHzMemory: 4 GB RAMGraphics: NVIDIA 9800 GT 1GB / AMD HD 4870 1GB (DX 10, 10.1, 11)Storage: 72 GB available spaceSound Card: 100% DirectX 10 compatibleAdditional Notes: Over time downloadable content and programming changes will change the system requirements for this game.  Please refer to your hardware manufacturer and www.rockstargames.com/support for current compatibility information. Some system components such as mobile chipsets, integrated, and AGP graphics cards may be incompatible. Unlisted specifications may not be supported by publisher.     Other requirements:  Installation and online play requires log-in to Rockstar Games Social Club (13+) network; internet connection required for activation, online play, and periodic entitlement verification; software installations required including Rockstar Games Social Club platform, DirectX , Chromium, and Microsoft Visual C++ 2008 sp1 Redistributable Package, and authentication software that recognizes certain hardware attributes for entitlement, digital rights management, system, and other support purposes.     SINGLE USE SERIAL CODE REGISTRATION VIA INTERNET REQUIRED; REGISTRATION IS LIMITED TO ONE ROCKSTAR GAMES SOCIAL CLUB ACCOUNT (13+) PER SERIAL CODE; ONLY ONE PC LOG-IN ALLOWED PER SOCIAL CLUB ACCOUNT AT ANY TIME; SERIAL CODE(S) ARE NON-TRANSFERABLE ONCE USED; SOCIAL CLUB ACCOUNTS ARE NON-TRANSFERABLE.  Partner Requirements:  Please check the terms of service of this site before purchasing this software.',
      'recommended': 'Recommended:OS: Windows 10 64 Bit, Windows 8.1 64 Bit, Windows 8 64 Bit, Windows 7 64 Bit Service Pack 1Processor: Intel Core i5 3470 @ 3.2GHz (4 CPUs) / AMD X8 FX-8350 @ 4GHz (8 CPUs)Memory: 8 GB RAMGraphics: NVIDIA GTX 660 2GB / AMD HD 7870 2GBStorage: 72 GB available spaceSound Card: 100% DirectX 10 compatibleAdditional Notes:'},
     'requirements_ru': None},
    {'platform': {'id': 18,
      'name': 'PlayStation 4',
      'slug': 'playstation4',
      'image': None,
      'year_end': None,
      'year_start': None,
      'games_count': 6988,
      'image_background': 'https://media.rawg.io/media/games/b45/b45575f34285f2c4479c9a5f719d972e.jpg'},
     'released_at': '2013-09-17',
     'requirements_en': None,
     'requirements_ru': None},
    {'platform': {'id': 14,
      'name': 'Xbox 360',
      'slug': 'xbox360',
      'image': None,
      'year_end': None,
      'year_start': None,
      'games_count': 2828,
      'image_background': 'https://media.rawg.io/media/games/5c0/5c0dd63002cb23f804aab327d40ef119.jpg'},
     'released_at': '2013-09-17',
     'requirements_en': None,
     'requirements_ru': None},
    {'platform': {'id': 1,
      'name': 'Xbox One',
      'slug': 'xbox-one',
      'image': None,
      'year_end': None,
      'year_start': None,
      'games_count': 5739,
      'image_background': 'https://media.rawg.io/media/games/511/5118aff5091cb3efec399c808f8c598f.jpg'},
     'released_at': '2013-09-17',
     'requirements_en': None,
     'requirements_ru': None}],
   'parent_platforms': [{'platform': {'id': 1, 'name': 'PC', 'slug': 'pc'}},
    {'platform': {'id': 2, 'name': 'PlayStation', 'slug': 'playstation'}},
    {'platform': {'id': 3, 'name': 'Xbox', 'slug': 'xbox'}}],
   'genres': [{'id': 4,
     'name': 'Action',
     'slug': 'action',
     'games_count': 191553,
     'image_background': 'https://media.rawg.io/media/games/73e/73eecb8909e0c39fb246f457b5d6cbbe.jpg'}],
   'stores': [{'id': 290376,
     'store': {'id': 1,
      'name': 'Steam',
      'slug': 'steam',
      'domain': 'store.steampowered.com',
      'games_count': 123289,
      'image_background': 'https://media.rawg.io/media/games/34b/34b1f1850a1c06fd971bc6ab3ac0ce0e.jpg'}},
    {'id': 290375,
     'store': {'id': 3,
      'name': 'PlayStation Store',
      'slug': 'playstation-store',
      'domain': 'store.playstation.com',
      'games_count': 8075,
      'image_background': 'https://media.rawg.io/media/games/021/021c4e21a1824d2526f925eff6324653.jpg'}},
    {'id': 438095,
     'store': {'id': 11,
      'name': 'Epic Games',
      'slug': 'epic-games',
      'domain': 'epicgames.com',
      'games_count': 1451,
      'image_background': 'https://media.rawg.io/media/games/1bd/1bd2657b81eb0c99338120ad444b24ff.jpg'}},
    {'id': 290377,
     'store': {'id': 7,
      'name': 'Xbox 360 Store',
      'slug': 'xbox360',
      'domain': 'marketplace.xbox.com',
      'games_count': 1915,
      'image_background': 'https://media.rawg.io/media/games/bc0/bc06a29ceac58652b684deefe7d56099.jpg'}},
    {'id': 290378,
     'store': {'id': 2,
      'name': 'Xbox Store',
      'slug': 'xbox-store',
      'domain': 'microsoft.com',
      'games_count': 4938,
      'image_background': 'https://media.rawg.io/media/games/34b/34b1f1850a1c06fd971bc6ab3ac0ce0e.jpg'}}],
   'clip': None,
   'tags': [{'id': 31,
     'name': 'Singleplayer',
     'slug': 'singleplayer',
     'language': 'eng',
     'games_count': 250826,
     'image_background': 'https://media.rawg.io/media/games/618/618c2031a07bbff6b4f611f10b6bcdbc.jpg'},
    {'id': 40847,
     'name': 'Steam Achievements',
     'slug': 'steam-achievements',
     'language': 'eng',
     'games_count': 51709,
     'image_background': 'https://media.rawg.io/media/games/b45/b45575f34285f2c4479c9a5f719d972e.jpg'},
    {'id': 7,
     'name': 'Multiplayer',
     'slug': 'multiplayer',
     'language': 'eng',
     'games_count': 42553,
     'image_background': 'https://media.rawg.io/media/games/157/15742f2f67eacff546738e1ab5c19d20.jpg'},
    {'id': 40836,
     'name': 'Full controller support',
     'slug': 'full-controller-support',
     'language': 'eng',
     'games_count': 24144,
     'image_background': 'https://media.rawg.io/media/games/16b/16b1b7b36e2042d1128d5a3e852b3b2f.jpg'},
    {'id': 13,
     'name': 'Atmospheric',
     'slug': 'atmospheric',
     'language': 'eng',
     'games_count': 39707,
     'image_background': 'https://media.rawg.io/media/games/562/562553814dd54e001a541e4ee83a591c.jpg'},
    {'id': 42,
     'name': 'Great Soundtrack',
     'slug': 'great-soundtrack',
     'language': 'eng',
     'games_count': 3450,
     'image_background': 'https://media.rawg.io/media/games/bc0/bc06a29ceac58652b684deefe7d56099.jpg'},
    {'id': 24,
     'name': 'RPG',
     'slug': 'rpg',
     'language': 'eng',
     'games_count': 26624,
     'image_background': 'https://media.rawg.io/media/games/26d/26d4437715bee60138dab4a7c8c59c92.jpg'},
    {'id': 18,
     'name': 'Co-op',
     'slug': 'co-op',
     'language': 'eng',
     'games_count': 14391,
     'image_background': 'https://media.rawg.io/media/games/6fc/6fcf4cd3b17c288821388e6085bb0fc9.jpg'},
    {'id': 36,
     'name': 'Open World',
     'slug': 'open-world',
     'language': 'eng',
     'games_count': 9265,
     'image_background': 'https://media.rawg.io/media/games/490/49016e06ae2103881ff6373248843069.jpg'},
    {'id': 411,
     'name': 'cooperative',
     'slug': 'cooperative',
     'language': 'eng',
     'games_count': 6588,
     'image_background': 'https://media.rawg.io/media/games/2ba/2bac0e87cf45e5b508f227d281c9252a.jpg'},
    {'id': 8,
     'name': 'First-Person',
     'slug': 'first-person',
     'language': 'eng',
     'games_count': 37394,
     'image_background': 'https://media.rawg.io/media/games/d82/d82990b9c67ba0d2d09d4e6fa88885a7.jpg'},
    {'id': 149,
     'name': 'Third Person',
     'slug': 'third-person',
     'language': 'eng',
     'games_count': 14710,
     'image_background': 'https://media.rawg.io/media/games/5c0/5c0dd63002cb23f804aab327d40ef119.jpg'},
    {'id': 4,
     'name': 'Funny',
     'slug': 'funny',
     'language': 'eng',
     'games_count': 28841,
     'image_background': 'https://media.rawg.io/media/games/20a/20aa03a10cda45239fe22d035c0ebe64.jpg'},
    {'id': 37,
     'name': 'Sandbox',
     'slug': 'sandbox',
     'language': 'eng',
     'games_count': 8513,
     'image_background': 'https://media.rawg.io/media/games/13a/13a528ac9cf48bbb6be5d35fe029336d.jpg'},
    {'id': 123,
     'name': 'Comedy',
     'slug': 'comedy',
     'language': 'eng',
     'games_count': 14864,
     'image_background': 'https://media.rawg.io/media/games/ffe/ffed87105b14f5beff72ff44a7793fd5.jpg'},
    {'id': 150,
     'name': 'Third-Person Shooter',
     'slug': 'third-person-shooter',
     'language': 'eng',
     'games_count': 4168,
     'image_background': 'https://media.rawg.io/media/games/f87/f87457e8347484033cb34cde6101d08d.jpg'},
    {'id': 62,
     'name': 'Moddable',
     'slug': 'moddable',
     'language': 'eng',
     'games_count': 1136,
     'image_background': 'https://media.rawg.io/media/games/d58/d588947d4286e7b5e0e12e1bea7d9844.jpg'},
    {'id': 144,
     'name': 'Crime',
     'slug': 'crime',
     'language': 'eng',
     'games_count': 3269,
     'image_background': 'https://media.rawg.io/media/games/6cc/6cc68fa183b905ac9d85efb9797776f6.jpg'},
    {'id': 62349,
     'name': 'vr mod',
     'slug': 'vr-mod',
     'language': 'eng',
     'games_count': 17,
     'image_background': 'https://media.rawg.io/media/screenshots/1bb/1bb3f78f0fe43b5d5ca2f3da5b638840.jpg'}],
   'esrb_rating': {'id': 4, 'name': 'Mature', 'slug': 'mature'},
   'short_screenshots': [{'id': -1,
     'image': 'https://media.rawg.io/media/games/20a/20aa03a10cda45239fe22d035c0ebe64.jpg'},
    {'id': 1827223,
     'image': 'https://media.rawg.io/media/screenshots/f95/f9518b1d99210c0cae21fc09e95b4e31.jpg'},
    {'id': 1827225,
     'image': 'https://media.rawg.io/media/screenshots/a5c/a5c95ea539c87d5f538763e16e18fb99.jpg'},
    {'id': 1827226,
     'image': 'https://media.rawg.io/media/screenshots/a7e/a7e990bc574f4d34e03b5926361d1ee7.jpg'},
    {'id': 1827228,
     'image': 'https://media.rawg.io/media/screenshots/eb0/eb0a2c0de9194a635fc0cd04f5a29ae7.jpg'},
    {'id': 1827229,
     'image': 'https://media.rawg.io/media/screenshots/ec7/ec7f05fb82290fea9647b7879fe9a6bf.jpg'},
    {'id': 1827230,
     'image': 'https://media.rawg.io/media/screenshots/260/260559fbefce0b36c66ae5e280c7d774.jpg'}]},
  {'id': 3328,
   'slug': 'the-witcher-3-wild-hunt',
   'name': 'The Witcher 3: Wild Hunt',
   'released': '2015-05-18',
   'tba': False,
   'background_image': 'https://media.rawg.io/media/games/618/618c2031a07bbff6b4f611f10b6bcdbc.jpg',
   'rating': 4.64,
   'rating_top': 5,
   'ratings': [{'id': 5,
     'title': 'exceptional',
     'count': 5585,
     'percent': 76.52},
    {'id': 4, 'title': 'recommended', 'count': 1195, 'percent': 16.37},
    {'id': 3, 'title': 'meh', 'count': 319, 'percent': 4.37},
    {'id': 1, 'title': 'skip', 'count': 200, 'percent': 2.74}],
   'ratings_count': 7180,
   'reviews_text_count': 83,
   'added': 22188,
   'added_by_status': {'yet': 1214,
    'owned': 12885,
    'beaten': 5304,
    'toplay': 856,
    'dropped': 1031,
    'playing': 898},
   'metacritic': 92,
   'playtime': 43,
   'suggestions_count': 688,
   'updated': '2026-04-06T20:17:45',
   'user_game': None,
   'reviews_count': 7299,
   'saturated_color': '0f0f0f',
   'dominant_color': '0f0f0f',
   'platforms': [{'platform': {'id': 187,
      'name': 'PlayStation 5',
      'slug': 'playstation5',
      'image': None,
      'year_end': None,
      'year_start': 2020,
      'games_count': 1462,
      'image_background': 'https://media.rawg.io/media/games/34b/34b1f1850a1c06fd971bc6ab3ac0ce0e.jpg'},
     'released_at': '2015-05-18',
     'requirements_en': None,
     'requirements_ru': None},
    {'platform': {'id': 186,
      'name': 'Xbox Series S/X',
      'slug': 'xbox-series-x',
      'image': None,
      'year_end': None,
      'year_start': 2020,
      'games_count': 1241,
      'image_background': 'https://media.rawg.io/media/games/b4a/b4adf80c36e267b35acc3497ed2af19c.jpg'},
     'released_at': '2015-05-18',
     'requirements_en': None,
     'requirements_ru': None},
    {'platform': {'id': 5,
      'name': 'macOS',
      'slug': 'macos',
      'image': None,
      'year_end': None,
      'year_start': None,
      'games_count': 108039,
      'image_background': 'https://media.rawg.io/media/games/d58/d588947d4286e7b5e0e12e1bea7d9844.jpg'},
     'released_at': '2015-05-18',
     'requirements_en': None,
     'requirements_ru': None},
    {'platform': {'id': 18,
      'name': 'PlayStation 4',
      'slug': 'playstation4',
      'image': None,
      'year_end': None,
      'year_start': None,
      'games_count': 6988,
      'image_background': 'https://media.rawg.io/media/games/b45/b45575f34285f2c4479c9a5f719d972e.jpg'},
     'released_at': '2015-05-18',
     'requirements_en': None,
     'requirements_ru': None},
    {'platform': {'id': 7,
      'name': 'Nintendo Switch',
      'slug': 'nintendo-switch',
      'image': None,
      'year_end': None,
      'year_start': None,
      'games_count': 5767,
      'image_background': 'https://media.rawg.io/media/games/1f4/1f47a270b8f241e4676b14d39ec620f7.jpg'},
     'released_at': '2015-05-18',
     'requirements_en': None,
     'requirements_ru': None},
    {'platform': {'id': 4,
      'name': 'PC',
      'slug': 'pc',
      'image': None,
      'year_end': None,
      'year_start': None,
      'games_count': 560648,
      'image_background': 'https://media.rawg.io/media/games/736/73619bd336c894d6941d926bfd563946.jpg'},
     'released_at': '2015-05-18',
     'requirements_en': None,
     'requirements_ru': None},
    {'platform': {'id': 1,
      'name': 'Xbox One',
      'slug': 'xbox-one',
      'image': None,
      'year_end': None,
      'year_start': None,
      'games_count': 5739,
      'image_background': 'https://media.rawg.io/media/games/511/5118aff5091cb3efec399c808f8c598f.jpg'},
     'released_at': '2015-05-18',
     'requirements_en': None,
     'requirements_ru': None}],
   'parent_platforms': [{'platform': {'id': 1, 'name': 'PC', 'slug': 'pc'}},
    {'platform': {'id': 2, 'name': 'PlayStation', 'slug': 'playstation'}},
    {'platform': {'id': 3, 'name': 'Xbox', 'slug': 'xbox'}},
    {'platform': {'id': 5, 'name': 'Apple Macintosh', 'slug': 'mac'}},
    {'platform': {'id': 7, 'name': 'Nintendo', 'slug': 'nintendo'}}],
   'genres': [{'id': 4,
     'name': 'Action',
     'slug': 'action',
     'games_count': 191553,
     'image_background': 'https://media.rawg.io/media/games/73e/73eecb8909e0c39fb246f457b5d6cbbe.jpg'},
    {'id': 5,
     'name': 'RPG',
     'slug': 'role-playing-games-rpg',
     'games_count': 61953,
     'image_background': 'https://media.rawg.io/media/games/d82/d82990b9c67ba0d2d09d4e6fa88885a7.jpg'}],
   'stores': [{'id': 354780,
     'store': {'id': 5,
      'name': 'GOG',
      'slug': 'gog',
      'domain': 'gog.com',
      'games_count': 7244,
      'image_background': 'https://media.rawg.io/media/games/587/587588c64afbff80e6f444eb2e46f9da.jpg'}},
    {'id': 3565,
     'store': {'id': 3,
      'name': 'PlayStation Store',
      'slug': 'playstation-store',
      'domain': 'store.playstation.com',
      'games_count': 8075,
      'image_background': 'https://media.rawg.io/media/games/021/021c4e21a1824d2526f925eff6324653.jpg'}},
    {'id': 305376,
     'store': {'id': 1,
      'name': 'Steam',
      'slug': 'steam',
      'domain': 'store.steampowered.com',
      'games_count': 123289,
      'image_background': 'https://media.rawg.io/media/games/34b/34b1f1850a1c06fd971bc6ab3ac0ce0e.jpg'}},
    {'id': 312313,
     'store': {'id': 2,
      'name': 'Xbox Store',
      'slug': 'xbox-store',
      'domain': 'microsoft.com',
      'games_count': 4938,
      'image_background': 'https://media.rawg.io/media/games/34b/34b1f1850a1c06fd971bc6ab3ac0ce0e.jpg'}},
    {'id': 676022,
     'store': {'id': 6,
      'name': 'Nintendo Store',
      'slug': 'nintendo',
      'domain': 'nintendo.com',
      'games_count': 9150,
      'image_background': 'https://media.rawg.io/media/games/be0/be01c3d7d8795a45615da139322ca080.jpg'}}],
   'clip': None,
   'tags': [{'id': 31,
     'name': 'Singleplayer',
     'slug': 'singleplayer',
     'language': 'eng',
     'games_count': 250826,
     'image_background': 'https://media.rawg.io/media/games/618/618c2031a07bbff6b4f611f10b6bcdbc.jpg'},
    {'id': 40836,
     'name': 'Full controller support',
     'slug': 'full-controller-support',
     'language': 'eng',
     'games_count': 24144,
     'image_background': 'https://media.rawg.io/media/games/16b/16b1b7b36e2042d1128d5a3e852b3b2f.jpg'},
    {'id': 13,
     'name': 'Atmospheric',
     'slug': 'atmospheric',
     'language': 'eng',
     'games_count': 39707,
     'image_background': 'https://media.rawg.io/media/games/562/562553814dd54e001a541e4ee83a591c.jpg'},
    {'id': 42,
     'name': 'Great Soundtrack',
     'slug': 'great-soundtrack',
     'language': 'eng',
     'games_count': 3450,
     'image_background': 'https://media.rawg.io/media/games/bc0/bc06a29ceac58652b684deefe7d56099.jpg'},
    {'id': 24,
     'name': 'RPG',
     'slug': 'rpg',
     'language': 'eng',
     'games_count': 26624,
     'image_background': 'https://media.rawg.io/media/games/26d/26d4437715bee60138dab4a7c8c59c92.jpg'},
    {'id': 118,
     'name': 'Story Rich',

In [27]:
juegos.keys()

dict_keys(['count', 'next', 'previous', 'results', 'seo_title', 'seo_description', 'seo_keywords', 'seo_h1', 'noindex', 'nofollow', 'description', 'filters', 'nofollow_collections'])

In [30]:
count = juegos['count']
print("El número de juegos que RAWG tiene registrados en total es", count)

El número de juegos que RAWG tiene registrados en total es 898364

### Part B — Category Analysis

B1

What is the top 5 highest rated games of all time according to Metacritic?

Show: name, rating, and metacritic score.

En primer lugar jalamos el mismo url que en la primera pero con un pequeño artificio, ordenamos la informacion de forma descendente por metacritic dado que nos dicen que busquemos los 5 mejores juegos rateados SEGUN metacritic. Creamos una tabla donde extraemos para los primeros 5 ordenados de mayor a menos es decir el top 5 su name, rating, metacritic para luego exportarlo a un dataframe.

In [143]:
url1 = f"https://api.rawg.io/api/games?key={api_key}&ordering=-metacritic"
info1 = requests.get(url1)

In [210]:
critic = info1.json()

table = []

for i in range(5):
    name = critic['results'][i]['name']
    rating = critic['results'][i]['rating']
    metacritic = critic['results'][i]['metacritic']

    fila = name, rating, metacritic
    table.append(fila)

df = pd.DataFrame(table, columns=["name", "rating", "metacritic"])
df

                                   name  rating  metacritic
0  The Legend of Zelda: Ocarina of Time    4.38          99
1                    Soulcalibur (1998)    0.00          98
2                           Soulcalibur    4.38          98
3                     Baldur's Gate III    4.44          97
4                         Metroid Prime    4.35          97

B2

What are the 10 best games available on Steam (store_id=1)?

Show name, rating, and metacritic score.

Es el mismo url que en la anterior pregunta solo que ahora tambien filtramos por stores donde como se nos dio, el store_id = 1 para la tienda de Steam por lo que extraemos de esa url su formato JSON para luego en una tabla extraer el name, raitng and metacritic de los 10 primeros que dado que estan ordenados de forma descendente por metacritic nos daran los 10 mejores juegos de steam ordenados por metacritic. Finalmente lo exportamos a un dataframe.

In [208]:
url2 = f"https://api.rawg.io/api/games?key={api_key}&stores=1&ordering=-metacritic"
info2 = requests.get(url2)

In [211]:
steam_rating = info2.json()

table1 = []

for i in range(10):
    name = steam_rating['results'][i]['name']
    rating = steam_rating['results'][i]['rating']
    metacritic = steam_rating['results'][i]['metacritic']

    fila = name, rating, metacritic
    table1.append(fila)

df1 = pd.DataFrame(table1, columns=["name", "rating", "metacritic"])
df1

                                    name  rating  metacritic
0                      Baldur's Gate III    4.44          97
1                    Half-Life 2: Update    4.13          96
2                              Half-Life    4.38          96
3                  Red Dead Redemption 2    4.59          96
4                            Half-Life 2    4.48          96
5                               BioShock    4.36          96
6  Grand Theft Auto IV: Complete Edition    4.57          95
7               Divinity: Original Sin 2    4.38          95
8                               Portal 2    4.58          95
9                    Red Dead Redemption    4.42          95

### Part C — Comparisons  

C1

Compare the top 5 games on PC (platform_id=4) vs top 5 on PS5 (platform_id=187).

Which platform has the highest rated games?

Extraemos las urls para las plataformas de PC (platform_id=4) y PS5 (platform_id=187) y realizamos el mismo proceso de antes para un top 5 mejores juegos de cada plataforma. Finalmente comparamos las columnas de rating de PC vs PS5 lo que nos da como resultado que los juegos de PC tienen mejor rating.

In [215]:
url3 = f"https://api.rawg.io/api/games?key={api_key}&platforms=4&ordering=-rating"
info3 = requests.get(url3)

In [218]:
pc_games = info3.json()
table2 = []

for i in range(5):
    name = pc_games['results'][i]['name']
    rating = pc_games['results'][i]['rating']
    metacritic = pc_games['results'][i]['metacritic']

    fila = name, rating, metacritic
    table2.append(fila)

df2 = pd.DataFrame(table2, columns=["name", "rating", "metacritic"])
df2

                                                name  rating  metacritic
0                               The Elder Scrolls VI    4.86         NaN
1  Warhammer 40,000: Dawn of War - Definitive Edi...    4.83         NaN
2                     No Case Should Remain Unsolved    4.83         NaN
3          The Witcher 3: Wild Hunt – Blood and Wine    4.81        92.0
4         The Witcher 3 Wild Hunt - Complete Edition    4.80        92.0

In [219]:
url4 = f"https://api.rawg.io/api/games?key={api_key}&platforms=187&ordering=-rating"
info4 = requests.get(url4)

In [221]:
ps5_games = info4.json()
table3 = []

for i in range(5):
    name = ps5_games['results'][i]['name']
    rating = ps5_games['results'][i]['rating']
    metacritic = ps5_games['results'][i]['metacritic']

    fila = name, rating, metacritic
    table3.append(fila)

df3 = pd.DataFrame(table3, columns=["name", "rating", "metacritic"])
df3

                                         name  rating  metacritic
0  The Witcher 3 Wild Hunt - Complete Edition    4.80        92.0
1                             Persona 5 Royal    4.75        94.0
2             Cyberpunk 2077: Phantom Liberty    4.71         NaN
3            The Binding of Isaac: Repentance    4.69         NaN
4                       The Last of Us Part I    4.67         NaN

In [225]:
df3['rating'] > df2['rating']

0    False
1    False
2    False
3    False
4    False
Name: rating, dtype: bool

C2

Choose 3 famous games and build a comparison table with:

name, rating, metacritic, genres, and platforms.

Ahora hacemos un request de los mejores juegos ordenados por rating y seleccionamos los juegos de nuestra preferencia (3), despues extraemos de platforms las diferentes plataformas donde se pueden jugar dichos juegos para cada uno de los 3 juegos seleccionados. Finalmente exportamos la data a un dataframe donde esta el name, rating, metacritic and platforms que es lo que agregamos anteriormente.

In [226]:
url5 = f"https://api.rawg.io/api/games?key={api_key}&ordering=-rating"
info5 = requests.get(url5)

In [244]:
best_rated_games = info5.json()
table4 = []

for i in range(20):
    name = best_rated_games['results'][i]['name']
    rating = best_rated_games['results'][i]['rating']
    metacritic = best_rated_games['results'][i]['metacritic']

    fila = name, rating, metacritic
    table4.append(fila)

df4 = pd.DataFrame(table4, columns=["name", "rating", "metacritic"])
df4

                                                 name  rating  metacritic
0                                The Elder Scrolls VI    4.86         NaN
1   Warhammer 40,000: Dawn of War - Definitive Edi...    4.83         NaN
2                      No Case Should Remain Unsolved    4.83         NaN
3                                            Gimmick!    4.83         NaN
4             Super Robot Taisen: Original Generation    4.83         NaN
5           The Witcher 3: Wild Hunt – Blood and Wine    4.81        92.0
6          The Witcher 3 Wild Hunt - Complete Edition    4.80        92.0
7          The Witcher 3: Wild Hunt – Hearts of Stone    4.76        90.0
8                                     Persona 5 Royal    4.75        94.0
9                                 Mass Effect Trilogy    4.75         NaN
10                                       Esoteric Ebb    4.71         NaN
11                    Cyberpunk 2077: Phantom Liberty    4.71         NaN
12        Sonic Triple Trouble 16-Bit (NoahNCopeland)    4.71         NaN
13                        Bloodborne: The Old Hunters    4.71         NaN
14                                Adventure Island IV    4.71         NaN
15                                      Guilty Parade    4.71         NaN
16                            Godzilla Save the Earth    4.71         NaN
17                                             Arcaea    4.71         NaN
18                      Victoria 2: Heart of Darkness    4.71         NaN
19        Harvest Moon: Friends of Mineral Town (Wii)    4.71         NaN

In [291]:
table5 = []
for x in [6, 8, 11]:
    name = best_rated_games['results'][x]['name']
    rating = best_rated_games['results'][x]['rating']
    metacritic = best_rated_games['results'][x]['metacritic']
    platforms = []
    i = 0
    while True:
        try:
            platform = best_rated_games['results'][x]['platforms'][i]['platform']['name']
            platforms.append(platform)
            i = i + 1
        except IndexError:
            print("Se acabaron los elementos")
            break
    fila = name, rating, metacritic, platforms
    table5.append(fila)

df5 = pd.DataFrame(table5, columns=["name", "rating", "metacritic", "platforms"])
df5

Se acabaron los elementos
Se acabaron los elementos
Se acabaron los elementos

,name,rating,metacritic,platforms
0,The Witcher 3 Wild Hunt - Complete Edition,4.80,92.0,"[Xbox One, Xbox Series S/X, PC, Nintendo Switc..."
1,Persona 5 Royal,4.75,94.0,"[Xbox Series S/X, PC, PlayStation 5, Nintendo ..."
2,Cyberpunk 2077: Phantom Liberty,4.71,NaN,"[PlayStation 5, Xbox Series S/X, PC]"

C3

Query the top 5 games from at least 4 different genres, calculate the average rating for each, and determine which genre produces the best games according to users.

En primer lugar sacamos los json files de los generos con ids del 1 al 5. Luego mediante appends hacemos un dataframe con columnas donde cada columna representa los ratings de los top 5 mejores juegos de cada genero. A continuacion se halla por columnas el promedio general de cada uno de los generos en cuanto a rating para ver que el que tiene mejor rating es el genre_5 por lo que buscamos en el json_5 que alberga la data del genero 5 para indagar que el genre_5 hace referencia a los juegos RPG.

In [317]:
data_json = {}

for i in [1,2,3,4,5]:
    genero = f"https://api.rawg.io/api/games?key={api_key}&genres={i}&ordering=-rating"
    informacion = requests.get(genero)

    data_json[f"json_{i}"] = informacion.json()

In [355]:
ratings = pd.DataFrame()
for x in [1,2,3,4,5]:
    tabla = []
    
    for i in range(5):
        rating = data_json[f"json_{x}"]['results'][i]['rating']
        tabla.append(rating)
    
    ratings[f"genre_{x}"] = tabla

ratings

   genre_1  genre_2  genre_3  genre_4  genre_5
0     4.67     4.75     4.83     4.86     4.86
1     4.67     4.71     4.80     4.83     4.81
2     4.62     4.67     4.75     4.75     4.80
3     4.58     4.67     4.71     4.71     4.76
4     4.58     4.62     4.71     4.71     4.75

In [382]:
fila = {}

for x in [1,2,3,4,5]:
    fila[f"genre_{x}"] = ratings[f"genre_{x}"].mean()

rating_mean = pd.DataFrame([fila])
rating_mean

   genre_1  genre_2  genre_3  genre_4  genre_5
0    4.624    4.684     4.76    4.772    4.796

In [384]:
mejor_genero = rating_mean.idxmax(axis=1)[0]
mejor_genero

'genre_5'

In [ ]:
data_json['json_5']['results'][1]['genres'][0]['name']

'RPG'

C4 

Compare the best games from 3 different years of your choice.

In which year were the games with the highest average metacritic score released?

Seleccionamos los datos de los años 2012, 2018 y 2020. Los ordenamos de manera descendente en metacritica para luego extraer los top 20 mejores juegos y sus respectivas metacriticas. Finalmente siguiendo pasos similares al anterior ejercicio, extraemos las columnas donde cada columna representa un año y sus filas los top 20 mejores reseñas de metacriticas. Finalmente hallamos un promedio y obtenemos que el año con mejores metacriticas en promedio es el 2020.

In [409]:
year_2012 = f"https://api.rawg.io/api/games?key={api_key}&dates=2012-01-01,2012-12-31&ordering=-metacritic"
year_2018 = f"https://api.rawg.io/api/games?key={api_key}&dates=2018-01-01,2018-12-31&ordering=-metacritic"
year_2020 = f"https://api.rawg.io/api/games?key={api_key}&dates=2020-01-01,2020-12-31&ordering=-metacritic"
info_2012 = requests.get(year_2012)
info_2018 = requests.get(year_2018)
info_2020 = requests.get(year_2020)

In [422]:
juegos_2012 = info_2012.json()
juegos_2018 = info_2018.json()
juegos_2020 = info_2020.json()

juegos = {
    2012: juegos_2012,
    2018: juegos_2018,
    2020: juegos_2020
}

In [430]:
metacritics = pd.DataFrame()
for x in [2012, 2018, 2020]:
    tabla = []

    for i in range(20):
        metacritic = juegos[x]['results'][i]['metacritic']
        tabla.append(metacritic)
    
    metacritics[x] = tabla

metacritics

    2012  2018  2020
0     92    96    94
1     92    94    93
2     92    94    93
3     91    93    93
4     91    91    92
5     91    91    92
6     91    90    91
7     90    90    90
8     90    90    90
9     90    90    90
10    89    90    90
11    89    89    89
12    89    89    89
13    89    89    89
14    88    88    89
15    88    88    88
16    88    88    88
17    88    87    88
18    88    87    88
19    88    86    87

In [431]:
fila = {}

for x in [2012, 2018, 2020]:
    fila[x] = metacritics[x].mean()

metacritics_mean = pd.DataFrame([fila])
metacritics_mean

   2012  2018   2020
0  89.7  90.0  90.15

In [435]:
mejor_año = metacritics_mean.idxmax(axis=1)[0]
print(mejor_año)

2020

C5

Export the top 20 games of all time to a CSV file named top20_rawg.csv inside the api/output/ folder.

Extraemos los datos de los 20 mejores juegos de todos los tiempos, similar al ejercicio 1 sin embargo esta vez seran 20 en lugar de 5 y añadiremos mas columnas de informacion como el released_date y main_genre. Creamos un dataframe y luego exportamos la data a un csv. Finalmente con el comando .head() se muestran los 5 primeros juegos con las columnas name, rating, metacritic, released_date y main_genre.

In [437]:
final_url = f"https://api.rawg.io/api/games?key={api_key}&ordering=-metacritic"
info_final = requests.get(final_url)

In [453]:
final_json = info_final.json()
table_final = []

for i in range(20):
    name = final_json['results'][i]['name']
    rating = final_json['results'][i]['rating']
    metacritic = final_json['results'][i]['metacritic']
    release_date = final_json['results'][i]['released']
    main_genre = final_json['results'][i]['genres'][0]['name']

    fila = name, rating, metacritic, release_date, main_genre
    table_final.append(fila)

df_final = pd.DataFrame(table_final, columns=["name", "rating", "metacritic", "release_date", "main_genre"])
df_final

,name,rating,metacritic,release_date,main_genre
0,The Legend of Zelda: Ocarina of Time,4.38,99,1998-11-21,Action
1,Soulcalibur (1998),0.00,98,1998-07-30,Fighting
2,Soulcalibur,4.38,98,1998-07-30,Action
3,Baldur's Gate III,4.44,97,2023-08-03,Adventure
4,Metroid Prime,4.35,97,2002-11-17,Action
5,Perfect Dark,3.98,97,2000-05-22,Action
6,Super Mario Odyssey,4.42,97,2017-10-27,Arcade
7,Super Mario Galaxy 2,4.34,97,2010-05-23,Platformer
8,Super Mario Galaxy,4.35,97,2007-11-01,Platformer
9,The Legend of Zelda: Breath of the Wild,4.47,97,2017-03-03,Action
10,Half-Life 2: Update,4.13,96,2015-03-27,Shooter
11,The Legend of Zelda: Tears of the Kingdom,4.38,96,2023-05-12,Action
12,Tekken 3,4.37,96,1997-03-20,Fighting
13,GoldenEye 007 (1997),4.37,96,1997-08-23,Shooter
14,Gran Turismo,4.33,96,1997-12-22,Racing
15,Metal Gear Solid 2: Sons of Liberty,4.34,96,2001-11-12,Action
16,Uncharted 2: Among Thieves,4.38,96,2009-10-13,Action
17,Half-Life,4.38,96,1998-11-19,Action
18,Half-Life 2,4.48,96,2004-11-16,Action
19,BioShock,4.36,96,2007-08-21,Action

In [455]:
df_final.to_csv(r'..\API\Output\top20_rawg.csv', index=False)

In [456]:
df_final.head()

,name,rating,metacritic,release_date,main_genre
0,The Legend of Zelda: Ocarina of Time,4.38,99,1998-11-21,Action
1,Soulcalibur (1998),0.00,98,1998-07-30,Fighting
2,Soulcalibur,4.38,98,1998-07-30,Action
3,Baldur's Gate III,4.44,97,2023-08-03,Adventure
4,Metroid Prime,4.35,97,2002-11-17,Action